version: '2'

services:
  db:
    image: mysql:5.7
    container_name: go-api-mysql.local
    hostname: go-api-mysql.local
    environment:
      - MYSQL_DATABASE=goapi
      - MYSQL_USER=goapi
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    networks:
      go-api:
        ipv4_address: 172.21.0.45
    expose:
      - "3306"
      
networks:
  go-api:
    external: true

#docker network create --subnet=172.25.0.0/24 --gateway=172.25.0.1 rhino